=== KParella/XMLDemo/XMLDemo/src/info/inetsolv/RequirementStudent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.hello.org/RequirementStudent/" 
 xmlns="http://www.hello.org/RequirementStudent/"
 elementFormDefault="qualified">
 
 <xs:element name="college">
 <xs:complexType>
 <xs:sequence>
 <xs:element name="student" minOccurs="1" maxOccurs="10" >
 <xs:complexType>
 <xs:sequence>
 
 <xs:element name="rollno">
 <xs:simpleType>
 <xs:restriction base="xs:integer">
 <xs:minInclusive value="1"></xs:minInclusive>
 <xs:maxInclusive value="500"></xs:maxInclusive>
 </xs:restriction>
 </xs:simpleType>
 </xs:element>
 
 <xs:element name="name">
 <xs:simpleType>
 <xs:restriction base="xs:string">
 <xs:minLength value="5"/>
 <xs:maxLength value="15"/>
 <xs:pattern value="([a-zA-Z])*"></xs:pattern>
 </xs:restriction>
 </xs:simpleType>
 </xs:element>
 
 <xs:element name="mno" minOccurs="3" maxOccurs="3">
 <xs:simpleType>
 <xs:restriction base="xs:integer">
<xs:pattern value="[0-9]{10}"></xs:pattern>
 </xs:restriction>
 </xs:simpleType>
 </xs:element>
 
 <xs:element name="address" minOccurs="0">
 <xs:complexType>
 <xs:sequence>
 <xs:element name="hno" type="xs:string" minOccurs="1" maxOccurs="1"/>
 <xs:element name="colony" type="xs:string" minOccurs="1" maxOccurs="1"/> 
 <xs:element name="city" type="xs:string" minOccurs="1" maxOccurs="1"/>
 </xs:sequence>
 <xs:attribute name="state" type="xs:string" fixed="Delhi"/>
 </xs:complexType>
 </xs:element>
 
 </xs:sequence>
 
 <xs:attribute name="type" type="xs:string" use="required"/>
 <xs:attribute name="course">
 <xs:simpleType>
 <xs:restriction base="xs:string">
 <xs:enumeration value="xml"/>
  <xs:enumeration value="html"/>
   <xs:enumeration value="java"/>
    <xs:enumeration value="Oracle"/>
     <xs:enumeration value="jee"/>
 </xs:restriction>
 </xs:simpleType>
 </xs:attribute> 
 </xs:complexType>
 </xs:element>
 
 </xs:sequence>
 </xs:complexType>
 </xs:element>
 
 
 
 
</xs:schema>

=== KParella/XMLDemo/XMLDemo/src/info/inetsolv/RequirementStudent.xml
<?xml version="1.0" encoding="UTF-8"?>
<college xmlns="http://www.hello.org/RequirementStudent/" 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:schemaLocation="http://www.hello.org/RequirementStudent/ RequirementStudent.xsd" >

<student type="regular">
<rollno>1</rollno>
<name>kuladeep</name>
<mno>7799365715</mno>
<mno>9849388192</mno>
<mno>9985993433</mno>
<address>
<hno>1</hno>
<colony>Ramannapet</colony>
<city>Gnt</city>
</address>
</student>

<student type="Distance">
<rollno>2</rollno>
<name>Sandeep</name>
<mno>6666666666</mno>
<mno>7777777777</mno>
<mno>5555555555</mno>
<address>
<hno>2</hno>
<colony>apet</colony>
<city>Hyd</city>
</address>
</student>




</college>
